### ISSUE TITLE
[FreeBSD] Test do not pass on FreeBSD 11.1 and 11.2

### ISSUE THREAD

**Issue by nekopep** [iustin/pylibacl#12]
Hi,
I'm running on a freebsd system (freenas 11.1 or 11.2).
I've setup an iocage with python36 and python37 and downloaded pylibacl_0.5.3.
if i run test: python3.7 test_acls.py I hit several error with the _file_ parameter of ACL class:

```
root@test:~/pylibacl-0.5.3/test # python3.7 test_acls.py

....E.FE...........EE
======================================================================
ERROR: testFromDir (__main__.LoadTests)
Test loading ACLs from a directory
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_acls.py", line 124, in testFromDir
    acl1 = posix1e.ACL(file=dname)
OSError: [Errno 22] Invalid argument

======================================================================
ERROR: testFromFile (__main__.LoadTests)
Test loading ACLs from a file
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_acls.py", line 118, in testFromFile
    acl1 = posix1e.ACL(file=fname)
OSError: [Errno 22] Invalid argument

======================================================================
ERROR: testDeleteDefault (__main__.WriteTests)
Test removing the default ACL
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_acls.py", line 202, in testDeleteDefault
    posix1e.delete_default(dname)
OSError: [Errno 22] Invalid argument

======================================================================
ERROR: testReapply (__main__.WriteTests)
Test re-applying an ACL
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_acls.py", line 209, in testReapply
    acl1.applyto(fname)
OSError: [Errno 22] Invalid argument

======================================================================
FAIL: testFromFd (__main__.LoadTests)
Test loading ACLs from a file descriptor
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_acls.py", line 135, in testFromFd
    self.assertTrue(acl1.valid(), "ACL read from fd should be valid")
AssertionError: False is not true : ACL read from fd should be valid

----------------------------------------------------------------------
Ran 21 tests in 0.014s

FAILED (failures=1, errors=4)
```

system:
```
root@test:~/pylibacl-0.5.3/test # uname -a
FreeBSD test 11.2-STABLE FreeBSD 11.2-STABLE #0 r325575+fc3d65faae6(freenas/11.2-stable): Wed Dec  5 15:08:42 EST 2018     root@nemesis.tn.ixsystems.com:/freenas-11.2-releng/freenas/_BE/objs/freenas-11.2-releng/freenas/_BE/os/sys/FreeNAS.amd64  amd64
```

Do you have any idea where I should dig to workaround this?

Thx!

**Comment by iustin** [comment]
Hi, thanks for the report! I haven't run a FreeBSD installation in a long while, so I'm not much surprised.

It would be good to run the test suite under the equivalent of strace, to see exactly which system calls fail. Some of these might be simply bugs related to how FreeBSD handles ACLs (i.e. pylibacl not knowing how to deal with FreeBSD), others could be things that FreeBSD doesn't support.

**Comment by nekopep** [comment]
Hello,
Ii just ran #truss python 3.7 test-acl.py.

```
<snip>
mmap(0x0,262144,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_ANON,-1,0x0) = 34390589440 (0x801d6c000)
munmap(0x801d6c000,262144)                       = 0 (0x0)
mmap(0x0,262144,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_ANON,-1,0x0) = 34390589440 (0x801d6c000)
munmap(0x801d6c000,262144)                       = 0 (0x0)
mmap(0x0,262144,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_ANON,-1,0x0) = 34390589440 (0x801d6c000)
munmap(0x801d6c000,262144)                       = 0 (0x0)
mmap(0x0,262144,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_ANON,-1,0x0) = 34390589440 (0x801d6c000)
stat("/root/pylibacl-0.5.3/test",{ mode=drwxr-xr-x ,inode=40544,size=4,blksize=131072 }) = 0 (0x0)
stat("/usr/local/lib/python3.7",{ mode=drwxr-xr-x ,inode=33322,size=208,blksize=131072 }) = 0 (0x0)
stat("/usr/local/lib/python3.7/lib-dynload",{ mode=drwxr-xr-x ,inode=35933,size=69,blksize=131072 }) = 0 (0x0)
stat("/usr/local/lib/python3.7/site-packages",{ mode=drwxr-xr-x ,inode=36534,size=11,blksize=131072 }) = 0 (0x0)
stat("/usr/local/lib/python3.7/site-packages/pylibacl-0.5.3-py3.7-freebsd-11.2-STABLE-amd64.egg",{ mode=drwxr-xr-x ,inode=40896,size=6,blksize=131072 }) = 0 (0x0)
stat("/usr/local/lib/python3.7/site-packages/pylibacl-0.5.3-py3.7-freebsd-11.2-STABLE-amd64.egg/posix1e.so",{ mode=-rwxr-xr-x ,inode=40898,size=39854,blksize=39936 }) = 0 (0x0)
openat(AT_FDCWD,"/usr/local/lib/python3.7/site-packages/pylibacl-0.5.3-py3.7-freebsd-11.2-STABLE-amd64.egg/posix1e.so",O_RDONLY|O_CLOEXEC|O_VERIFY,00) = 4 (0x4)
fstat(4,{ mode=-rwxr-xr-x ,inode=40898,size=39854,blksize=39936 }) = 0 (0x0)
mmap(0x0,4096,PROT_READ,MAP_PRIVATE|MAP_PREFAULT_READ,4,0x0) = 34366341120 (0x80064c000)
mmap(0x0,2129920,PROT_NONE,MAP_GUARD,-1,0x0)     = 34442174464 (0x804e9e000)
mmap(0x804e9e000,20480,PROT_READ|PROT_EXEC,MAP_PRIVATE|MAP_FIXED|MAP_NOCORE|MAP_PREFAULT_READ,4,0x0) = 34442174464 (0x804e9e000)
mmap(0x8050a2000,16384,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_FIXED|MAP_PREFAULT_READ,4,0x4000) = 34444288000 (0x8050a2000)
munmap(0x80064c000,4096)                         = 0 (0x0)
close(4)                                         = 0 (0x0)
clock_gettime(0,{ 1544388958.781539141 })        = 0 (0x0)
.write(2,".",1)                                  = 1 (0x1)
.write(2,".",1)                                  = 1 (0x1)
.write(2,".",1)                                  = 1 (0x1)
.write(2,".",1)                                  = 1 (0x1)
getpid()                                         = 69488 (0x10f70)
fstat(3,{ mode=crw-r--r-- ,inode=8,size=0,blksize=4096 }) = 0 (0x0)
read(3,"\M^U4m\M^CM\M-{\M-J4d\M-p\M-Z}p"...,2496) = 2496 (0x9c0)
fstat(3,{ mode=crw-r--r-- ,inode=8,size=0,blksize=4096 }) = 0 (0x0)
read(3,"\M-l\M-G\M-v\M-Nxj\^X@\M-E4\M^D"...,2496) = 2496 (0x9c0)
mkdir("./xattr-t6ngfbp3.test",0700)              = 0 (0x0)
__acl_get_file("./xattr-t6ngfbp3.test",ACL_TYPE_ACCESS,0x802706000) ERR#22 'Invalid argument'
rmdir("./xattr-t6ngfbp3.test")                   = 0 (0x0)
stat("test_acls.py",{ mode=-rw-r--r-- ,inode=40546,size=13375,blksize=13824 }) = 0 (0x0)
openat(AT_FDCWD,"test_acls.py",O_RDONLY|O_CLOEXEC,00) = 4 (0x4)
fstat(4,{ mode=-rw-r--r-- ,inode=40546,size=13375,blksize=13824 }) = 0 (0x0)
ioctl(4,TIOCGETA,0x7fffffffa200)                 ERR#25 'Inappropriate ioctl for device'
lseek(4,0x0,SEEK_CUR)                            = 0 (0x0)
read(4,"#\n#\n\n"""Unittests for the pos"...,13824) = 13375 (0x343f)
read(4,0x8021e1020,8192)                         = 0 (0x0)
close(4)                                         = 0 (0x0)
Ewrite(2,"E",1)                                  = 1 (0x1)
.write(2,".",1)                                  = 1 (0x1)
getpid()                                         = 69488 (0x10f70)
openat(AT_FDCWD,"./xattr-32d6gec5.test",O_RDWR|O_NOFOLLOW|O_CREAT|O_EXCL|O_CLOEXEC,0600) = 4 (0x4)
__getcwd("/root/pylibacl-0.5.3/test",1024)       = 0 (0x0)
fpathconf(0x4,0x40)                              = 1 (0x1)
__acl_get_fd(4,ACL_TYPE_NFS4,0x802716000)        = 0 (0x0)
unlink("/root/pylibacl-0.5.3/test/xattr-32d6gec5.test") = 0 (0x0)
stat("test_acls.py",{ mode=-rw-r--r-- ,inode=40546,size=13375,blksize=13824 }) = 0 (0x0)
Fwrite(2,"F",1)                                  = 1 (0x1)
getpid()                                         = 69488 (0x10f70)
openat(AT_FDCWD,"./xattr-hxwlvkx_.test",O_RDWR|O_NOFOLLOW|O_CREAT|O_EXCL|O_CLOEXEC,0600) = 5 (0x5)
__getcwd("/root/pylibacl-0.5.3/test",1024)       = 0 (0x0)
__acl_get_file("/root/pylibacl-0.5.3/test/xattr-hxwlvkx_.test",ACL_TYPE_ACCESS,0x80271c000) ERR#22 'Invalid argument'
unlink("/root/pylibacl-0.5.3/test/xattr-hxwlvkx_.test") = 0 (0x0)
stat("test_acls.py",{ mode=-rw-r--r-- ,inode=40546,size=13375,blksize=13824 }) = 0 (0x0)
Ewrite(2,"E",1)                                  = 1 (0x1)
.write(2,".",1)                                  = 1 (0x1)
.write(2,".",1)                                  = 1 (0x1)
.write(2,".",1)                                  = 1 (0x1)
.write(2,".",1)                                  = 1 (0x1)
.write(2,".",1)                                  = 1 (0x1)
.write(2,".",1)                                  = 1 (0x1)
.write(2,".",1)                                  = 1 (0x1)
.write(2,".",1)                                  = 1 (0x1)
.write(2,".",1)                                  = 1 (0x1)
.write(2,".",1)                                  = 1 (0x1)
.write(2,".",1)                                  = 1 (0x1)
getpid()                                         = 69488 (0x10f70)
mkdir("./xattr-ac2nk10h.test",0700)              = 0 (0x0)
__acl_delete_file("./xattr-ac2nk10h.test",ACL_TYPE_DEFAULT) ERR#22 'Invalid argument'
rmdir("./xattr-ac2nk10h.test")                   = 0 (0x0)
stat("test_acls.py",{ mode=-rw-r--r-- ,inode=40546,size=13375,blksize=13824 }) = 0 (0x0)
Ewrite(2,"E",1)                                  = 1 (0x1)
getpid()                                         = 69488 (0x10f70)
openat(AT_FDCWD,"./xattr-jbbdr996.test",O_RDWR|O_NOFOLLOW|O_CREAT|O_EXCL|O_CLOEXEC,0600) = 6 (0x6)
__getcwd("/root/pylibacl-0.5.3/test",1024)       = 0 (0x0)
fpathconf(0x6,0x40)                              = 1 (0x1)
__acl_get_fd(6,ACL_TYPE_NFS4,0x8027ac000)        = 0 (0x0)
fpathconf(0x6,0x40)                              = 1 (0x1)
__acl_set_fd(6,ACL_TYPE_NFS4,0x8027ac000)        = 0 (0x0)
unlink("/root/pylibacl-0.5.3/test/xattr-jbbdr996.test") = 0 (0x0)
stat("test_acls.py",{ mode=-rw-r--r-- ,inode=40546,size=13375,blksize=13824 }) = 0 (0x0)
Ewrite(2,"E",1)                                  = 1 (0x1)
clock_gettime(0,{ 1544388958.885475384 })        = 0 (0x0)

<snip>
```

There is several errors like:
 ERR#22 'Invalid argument'
or
 ERR#25 'Inappropriate ioctl for device'

Is it ok or strace really needed (looks more complicated to make it run under my iocage)

Best

**Comment by nekopep** [comment]
[full_logs.txt](https://github.com/iustin/pylibacl/files/2661000/err.txt)

**Comment by iustin** [comment]
It's OK, strace is not needed. I'll have to read the docs on, for example, when is __acl_get_file returning `Invalid argument`.

**Comment by tobiasbp** [comment]
I have the same problem. I'm running inside and iocage jail on FreeBSD 1.2 (FreeNAS):

`
root@automation-jail:~ # python3 test_acl.py 
s..ssssssss..E.FE.......s.......................E.E
======================================================================
ERROR: testFromDir (__main__.LoadTests)
Test loading ACLs from a directory
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_acl.py", line 132, in testFromDir
    acl1 = posix1e.ACL(file=dname)
OSError: [Errno 22] Invalid argument

======================================================================
ERROR: testFromFile (__main__.LoadTests)
Test loading ACLs from a file
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_acl.py", line 126, in testFromFile
    acl1 = posix1e.ACL(file=fname)
OSError: [Errno 22] Invalid argument

======================================================================
ERROR: testDeleteDefault (__main__.WriteTests)
Test removing the default ACL
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_acl.py", line 281, in testDeleteDefault
    posix1e.delete_default(dname)
OSError: [Errno 22] Invalid argument

======================================================================
ERROR: testReapply (__main__.WriteTests)
Test re-applying an ACL
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_acl.py", line 292, in testReapply
    acl1.applyto(fname)
OSError: [Errno 22] Invalid argument

======================================================================
FAIL: testFromFd (__main__.LoadTests)
Test loading ACLs from a file descriptor
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_acl.py", line 143, in testFromFd
    self.assertTrue(acl1.valid(), "ACL read from fd should be valid")
AssertionError: False is not true : ACL read from fd should be valid

----------------------------------------------------------------------
Ran 51 tests in 0.018s

FAILED (failures=1, errors=4, skipped=10)

`

**Comment by iustin** [comment]
Oops, forgot about this. I'll try to take a look in the next one or two weekends.

**Comment by iustin** [comment]
So, on a FreeBSD 12 machine: the 'E' are due to acls not being enabled on the filesystem. Once I used `tunefs`, all the errors go away, and only the 's' remains (because FreeBSD support is incomplete).

I'll note thsis in the documentation, and close the bug.
